// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjmP5Mc2gg0pfiDpQAakCyk0yvgOJj7Dg',
    appId: '1:385251936780:web:322e947cef150f72bc3c29',
    messagingSenderId: '385251936780',
    projectId: 'withyou-4e041',
    authDomain: 'withyou-4e041.firebaseapp.com',
    storageBucket: 'withyou-4e041.firebasestorage.app',
    measurementId: 'G-5VHFQ4RFNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCCZlzkGK9EshkDP0ygI-cGC_jqGZoEoo',
    appId: '1:385251936780:android:c7d9bab562b4da2dbc3c29',
    messagingSenderId: '385251936780',
    projectId: 'withyou-4e041',
    storageBucket: 'withyou-4e041.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaphC81kbZy5bsNPCQoXoYBVnSV5vbqJY',
    appId: '1:385251936780:ios:4b5899a725329260bc3c29',
    messagingSenderId: '385251936780',
    projectId: 'withyou-4e041',
    storageBucket: 'withyou-4e041.firebasestorage.app',
    iosBundleId: 'com.example.withyou',
  );
}
